### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by iammohdrazi** [pysharora/Artist-Portfolio#2]
Don't use hamburger menu , it's old . Instead use fixed top bar which will continue follow you. Try to make the front page more attractive like dark theme or light theme. Wrapping up, you can also select youself as a subject to this portfolio.
![ui_web](https://user-images.githubusercontent.com/48795472/126305512-5ef33ed0-c29c-46c9-89a1-97830982e680.png)

Other part of the ui look great. Good Work .

**Comment by pysharora** [comment]
Hey thank you for mentioning that. Right now, I am not working on this project and I am giving my time to something else. Will definitely take the suggestions and work on them.
